log:
  level: debug
  output_type: file
  logfile: logs/app.log
bind:
  host: 0.0.0.0
  port: 8080
  cert_file: ''
  key_file: ''
  print_access_log: true
  pprof: false
  shutdown_timeout: 30
  max_content_length: 67108864
  read_timeout: 20
  write_timeout: 40
  idle_timeout: 120
  read_buffer_size: 1024
  write_buffer_size: 1024
app:
  run_mode: 'debug'
