apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Manifest
metadata:
  name: sample
spec:
  arches:
    - amd64
  operatingSystems:
    - arch: amd64
      type: linux
      id: uos
      version: "Can't get the os version. Please edit it manually."
      osImage: UOS Server 20
      repository:
        iso:
          localPath:
          url:
  kubernetesDistributions:
    - type: kubernetes
      version: v1.24.9
  components:
    helm:
      version: v3.9.0
    cni:
      version: v0.9.1
    etcd:
      version: v3.4.13
    containerRuntimes:
      - type: docker
        version: 20.10.8
      - type: containerd
        version: 1.6.4
    calicoctl:
      version: v3.23.2
    crictl:
      version: v1.24.0
    docker-registry:
      version: "2"
    harbor:
      version: v2.5.3
    docker-compose:
      version: v2.26.1
  images:
    - registry.cn-beijing.aliyuncs.com/kubesphereio/cni:v3.23.2
    - registry.cn-beijing.aliyuncs.com/kubesphereio/coredns:1.8.6
    - registry.cn-beijing.aliyuncs.com/kubesphereio/haproxy:2.3
    - registry.cn-beijing.aliyuncs.com/kubesphereio/k8s-dns-node-cache:1.15.12
    - registry.cn-beijing.aliyuncs.com/kubesphereio/kube-apiserver:v1.24.9
    - registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controller-manager:v1.24.9
    - registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controllers:v3.23.2
    - registry.cn-beijing.aliyuncs.com/kubesphereio/kube-proxy:v1.24.9
    - registry.cn-beijing.aliyuncs.com/kubesphereio/kube-scheduler:v1.24.9
    - registry.cn-beijing.aliyuncs.com/kubesphereio/node:v3.23.2
    - registry.cn-beijing.aliyuncs.com/kubesphereio/pause:3.7
    - registry.cn-beijing.aliyuncs.com/kubesphereio/pod2daemon-flexvol:v3.23.2
    - registry.cn-beijing.aliyuncs.com/kubesphereio/typha:v3.23.2
  registry:
    auths: {}
